apiVersion: v1
kind: Service
metadata:
  name: nexus-service
spec:
  type: NodePort
  selector:
    app: nexus
  ports:
  - port: 8081        # service port inside cluster
    targetPort: 8081  # container port
    nodePort: 30002   # external port on Minikube node

